In [1]:
import torch 
import numpy as np
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
#Define Dataset
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [4]:
#Define DataLoader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [5]:
for xb,yb in train_dl:
    print(xb)
    print(yb)

tensor([[ 68.,  96.,  71.],
        [ 87., 134.,  58.],
        [ 87., 135.,  57.],
        [ 68.,  97.,  70.],
        [ 91.,  88.,  64.]])
tensor([[104., 118.],
        [119., 133.],
        [118., 134.],
        [102., 120.],
        [ 81., 101.]])
tensor([[ 69.,  96.,  70.],
        [101.,  44.,  37.],
        [ 88., 134.,  59.],
        [ 73.,  66.,  44.],
        [ 91.,  87.,  65.]])
tensor([[103., 119.],
        [ 21.,  38.],
        [118., 132.],
        [ 57.,  69.],
        [ 80., 102.]])
tensor([[ 74.,  66.,  43.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 92.,  87.,  64.],
        [103.,  43.,  36.]])
tensor([[ 57.,  69.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 82., 100.],
        [ 20.,  38.]])
tensor([[ 68.,  96.,  71.],
        [ 87., 134.,  58.],
        [ 87., 135.,  57.],
        [ 68.,  97.,  70.],
        [ 91.,  88.,  64.]])
tensor([[104., 118.],
        [119., 133.],
        [118., 134.],
        [102., 120.],
        [ 81., 

In [6]:
#Define the Model
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0040,  0.3481, -0.2721],
        [ 0.2369, -0.2125, -0.4454]], requires_grad=True)
Parameter containing:
tensor([0.1261, 0.3166], requires_grad=True)
Parameter containing:
tensor([[-0.0040,  0.3481, -0.2721],
        [ 0.2369, -0.2125, -0.4454]], requires_grad=True)
Parameter containing:
tensor([0.1261, 0.3166], requires_grad=True)


In [7]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0040,  0.3481, -0.2721],
         [ 0.2369, -0.2125, -0.4454]], requires_grad=True),
 Parameter containing:
 tensor([0.1261, 0.3166], requires_grad=True)]

[Parameter containing:
 tensor([[-0.0040,  0.3481, -0.2721],
         [ 0.2369, -0.2125, -0.4454]], requires_grad=True),
 Parameter containing:
 tensor([0.1261, 0.3166], requires_grad=True)]

In [8]:
#Generate Predictions
pre=model(inputs)
pre

tensor([[ 11.4532, -15.7814],
        [ 12.9763, -25.3338],
        [ 30.6385, -33.3820],
        [  4.6138,  -1.1408],
        [ 14.2176, -34.9170],
        [ 11.1011, -15.3321],
        [ 12.3561, -25.5667],
        [ 30.3623, -33.5905],
        [  4.9659,  -1.5901],
        [ 13.9495, -35.5992],
        [ 10.8330, -16.0144],
        [ 12.6242, -24.8845],
        [ 31.2587, -33.1490],
        [  4.8819,  -0.4585],
        [ 14.5698, -35.3663]], grad_fn=<AddmmBackward0>)

tensor([[ 11.4532, -15.7814],
        [ 12.9763, -25.3338],
        [ 30.6385, -33.3820],
        [  4.6138,  -1.1408],
        [ 14.2176, -34.9170],
        [ 11.1011, -15.3321],
        [ 12.3561, -25.5667],
        [ 30.3623, -33.5905],
        [  4.9659,  -1.5901],
        [ 13.9495, -35.5992],
        [ 10.8330, -16.0144],
        [ 12.6242, -24.8845],
        [ 31.2587, -33.1490],
        [  4.8819,  -0.4585],
        [ 14.5698, -35.3663]], grad_fn=<AddmmBackward0>)

In [9]:
#Define the Loss function
loss_fn=F.mse_loss
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(9872.2119, grad_fn=<MseLossBackward0>)
tensor(9872.2119, grad_fn=<MseLossBackward0>)


In [10]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [11]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [12]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 362.7610
Epoch [20/100], Loss: 526.3466
Epoch [30/100], Loss: 184.3727
Epoch [40/100], Loss: 184.0833
Epoch [50/100], Loss: 68.5057
Epoch [60/100], Loss: 173.5428
Epoch [70/100], Loss: 132.9616
Epoch [80/100], Loss: 76.6160
Epoch [90/100], Loss: 64.7966
Epoch [100/100], Loss: 31.3668
Epoch [10/100], Loss: 362.7610
Epoch [20/100], Loss: 526.3466
Epoch [30/100], Loss: 184.3727
Epoch [40/100], Loss: 184.0833
Epoch [50/100], Loss: 68.5057
Epoch [60/100], Loss: 173.5428
Epoch [70/100], Loss: 132.9616
Epoch [80/100], Loss: 76.6160
Epoch [90/100], Loss: 64.7966
Epoch [100/100], Loss: 31.3668


In [13]:
#Generate Predictions
pre=model(inputs)
pre

tensor([[ 58.2538,  72.3632],
        [ 78.6864,  96.7348],
        [123.9476, 138.6564],
        [ 27.6523,  48.0693],
        [ 92.0591, 105.9002],
        [ 57.0618,  71.4110],
        [ 77.8607,  96.0248],
        [123.9041, 138.8749],
        [ 28.8443,  49.0215],
        [ 92.4253, 106.1424],
        [ 57.4280,  71.6532],
        [ 77.4944,  95.7826],
        [124.7734, 139.3664],
        [ 27.2861,  47.8271],
        [ 93.2511, 106.8524]], grad_fn=<AddmmBackward0>)

tensor([[ 58.2538,  72.3632],
        [ 78.6864,  96.7348],
        [123.9476, 138.6564],
        [ 27.6523,  48.0693],
        [ 92.0591, 105.9002],
        [ 57.0618,  71.4110],
        [ 77.8607,  96.0248],
        [123.9041, 138.8749],
        [ 28.8443,  49.0215],
        [ 92.4253, 106.1424],
        [ 57.4280,  71.6532],
        [ 77.4944,  95.7826],
        [124.7734, 139.3664],
        [ 27.2861,  47.8271],
        [ 93.2511, 106.8524]], grad_fn=<AddmmBackward0>)

In [14]:
#Compare with Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])